import { Palette } from "../../Palette.slint";
import { HorizontalBox, TextEdit, LineEdit } from "std-widgets.slint";
import { TextField } from "../TextField.slint";
import { Button } from "../Button.slint";

export component LagerRow inherits Rectangle {

    in property <string> name;
    in property <float> price;
    in property <string> type;
    in property <string> amount;
    in property <string> rememberWhen;
    in property <string> description;
    callback clicked();
    
    border-radius: 6px;
    border-color: Palette.accent-color;
    border-width: 1px;
    
    HorizontalLayout {
        HorizontalLayout {
            padding: 8px;
            alignment: start;
            Text {
                text: name;
                width: 250px;
                font-size: Palette.font-size * 1px;
                overflow: TextOverflow.elide;
            }
    
            Rectangle {
                width: 120px;
            }
    
            Text {
                width: 200px;
                text: price;
                font-size: Palette.font-size * 1px;
                overflow: TextOverflow.elide;
            }
    
            Rectangle {
                width: 120px;
                
            }
    
            Text {
                width: 200px;
                text: amount;
                font-size: Palette.font-size * 1px;
                overflow: TextOverflow.elide;
            }
    
            Rectangle {
                width: 120px;
            }
    
            Text {
                width: 200px;
                text: type;
                font-size: Palette.font-size * 1px;
                overflow: TextOverflow.elide;
            }
    
            Rectangle {
                width: 120px;
            }
    
            Text {
                width: 200px;
                text: rememberWhen;
                font-size: Palette.font-size * 1px;
                overflow: TextOverflow.elide;
            }
    
            Rectangle {
                width: 100px;
            }
    
            Text {
                text: description;
                font-size: Palette.font-size * 1px;
                overflow: TextOverflow.elide;
            }
            Rectangle {width: 20px;}
            
        }
        Button {
            width: 30px;
            height: 30px;
            text: "X";
            clicked => {
                // TODO(jmeusel): someHow auslagern
            }
        }
        Rectangle {width: 20px;}
        Button {
            width: 30px;
            height: 30px;
            text: "✎";
            clicked => {
                // TODO(jmeusel): someHow auslagern
            }
        }
    }
}
