import { ProjectModel } from "ProjectModel.slint";
import { Material } from "MaterialModel.slint";
import { ClientModel } from "ClientModel.slint";

export global MockModel {

    //List of Projects
    in-out property <ProjectModel> projectModel;
    in-out property <[ProjectModel]> recentProjects;
    in-out property <ProjectModel> modelMock;
    in-out property <ProjectModel> modelMock1;
    in-out property <ProjectModel> modelMock2;
    in-out property <ProjectModel> modelMock3;

    in-out property <ProjectModel> modelMock4;
    in-out property <ProjectModel> modelMock5;
    in-out property <ProjectModel> modelMock6;
    in-out property <ProjectModel> modelMock7;
    in-out property <ProjectModel> modelMock8;
    in-out property <ProjectModel> modelMock9;
    in-out property <ProjectModel> modelMock10;
    in-out property <ProjectModel> modelMock11;
    modelMock: {name: "ProjName0", client: clientMock, project_start: "heute", project_deadline: "deadline", calculated_costs:2299.99, current_costs: 194.72, mats: []};
    modelMock1: {name: "ProjName1", client: clientMock, project_start: "heute", project_deadline: "deadline", calculated_costs:2199.99, current_costs: 194.72, mats: []};
    modelMock2: {name: "ProjName2", client: clientMock1, project_start: "heute", project_deadline: "deadline", calculated_costs:2929.99, current_costs: 194.72, mats: []};
    modelMock3: {name: "ProjName3", client: clientMock2, project_start: "heute", project_deadline: "deadline", calculated_costs:2929.99, current_costs: 194.72, mats: []};

    modelMock4: {name: "ProjName4", client: clientMock3, project_start: "heute", project_deadline: "deadline", calculated_costs:2979.99, current_costs: 194.72, mats: []};
    modelMock5: {name: "ProjName5", client: clientMock4, project_start: "heute", project_deadline: "deadline", calculated_costs:2959.99, current_costs: 19344.72, mats: []};
    modelMock6: {name: "ProjName6", client: clientMock, project_start: "heute", project_deadline: "deadline", calculated_costs:2949.99, current_costs: 19224.7212, mats: []};
    modelMock7: {name: "ProjName7", client: clientMock1, project_start: "heute", project_deadline: "deadline", calculated_costs:2939.99, current_costs: 19554.72, mats: []};
    modelMock8: {name: "ProjName8", client: clientMock2, project_start: "heute", project_deadline: "deadline", calculated_costs:99.99, current_costs: 19674.72, mats: []};
    modelMock9: {name: "ProjName9", client: clientMock3, project_start: "heute", project_deadline: "deadline", calculated_costs:2939.99, current_costs: 19424.72, mats: []};
    modelMock10: {name: "ProjName11", client: clientMock4, project_start: "heute", project_deadline: "deadline", calculated_costs:2939.99, current_costs: 1494.72, mats: []};
    modelMock11: {name: "ProjName12", client: clientMock, project_start: "heute", project_deadline: "deadline", calculated_costs:2939.949, current_costs: 19324.72, mats: []};

    recentProjects: [modelMock, modelMock1, modelMock2, modelMock];


    //List of Clients
    in-out property <[ClientModel]> clientList;
    in-out property <ClientModel> clientMock;
    in-out property <ClientModel> clientMock1;
    in-out property <ClientModel> clientMock2;
    in-out property <ClientModel> clientMock3;
    in-out property <ClientModel> clientMock4;

    clientMock: {firstName: "Max", lastName: "Mustermann", phone: 015730023345};
    clientMock1: {firstName: "Mus", lastName: "Meeeee", phone: 015730023345};
    clientMock2: {firstName: "Maas", lastName: "AAAAArNe", phone: 015730023345};
    clientMock3: {firstName: "kemo", lastName: "Bröld", phone: 015730023345};
    clientMock4: {firstName: "Tarek", lastName: "Asterix", phone: 015730023345};


    clientList: [clientMock, clientMock1, clientMock2, clientMock3, clientMock4];


    //List of Materials 
    in-out property <Material> mat1;
    in-out property <Material> mat2;
    in-out property <Material> mat3;
    in-out property <Material> mat4;
    in-out property <Material> mat5;
    in-out property <Material> mat6;
    in-out property <[Material]> materials;

    mat1: {name: "Material1 ", type: "schraube",description: "Description1", price: 11.11, quantity: 11};
    mat2: {name: "Material2", type: "dübel",description: "Description2", price: 22.22, quantity: 22};
    mat3: {name: "Material3", type: "CCCC",description: "Description3", price: 33.33, quantity: 33};
    mat4: {name: "Material4", type: "BSGE",description: "Description4", price: 44.44, quantity: 44};
    mat5: {name: "Material5", type: "AAAA",description: "Description5", price: 55.55, quantity: 55};
    mat6: {name: "Material6", type: "BBB",description: "Description6", price: 66.66, quantity: 66};

    materials: [mat1,mat2,mat3,mat4,mat5,mat6];

    //Full List of a lot of Projects
    in-out property <[ProjectModel]> allProjectsMockList;
    allProjectsMockList: [modelMock, modelMock1, modelMock2, modelMock3, modelMock4, modelMock5, modelMock6, modelMock7, modelMock8, modelMock9, modelMock10, modelMock11,];

    //Materials
    in-out property <Material> material1;
    in-out property <Material> material2;
    in-out property <Material> material3;
    in-out property <Material> material4;
    in-out property <Material> material5;
    in-out property <Material> material6;

    material1: {name: "Holz", description: "Ich und mein Holz", price: 49.85, quantity: 12};
    material2: {name: "Schraube 6x15", description: "Ich und die Schraube", price: 2.99, quantity: 36};
    material3: {name: "Dübel 2x5", description: "Ich und mein Dübel", price: 0.36, quantity: 12};
    material4: {name: "Nagel 0.5x4", description: "Nagelpiste", price: 2.12, quantity: 34};
    material5: {name: "Baum", description: "Ich und mein Baum", price: 299.66, quantity: 2};
    material6: {name: "Kohle", description: "Kooooooooohle ohne Ole", price: 44.12, quantity: 22};
    in-out property <[Material]> materialList;
    materialList: [material1,material2,material3,material4,material5, material6, mat1, mat2,mat3,mat4,mat5,mat6,];
    in property <ProjectModel> projectWithMats;
    projectWithMats: {name: "Project with mats", client: clientMock, project_start: "2024-04-18", project_deadline: "2024-06-02", calculated_costs:666, current_costs: 667-1, mats: materialList};


    //MAterial Types
    in-out property <[string]> materialTypesMock;
    materialTypesMock: ["Type", "Type_1", "Type_2", "Type_3", "Type_4", "LangesWortZumVerhaltensTest"];

    //ProjectView ehmalig: 
    // //recentProjects: ["Project", "Client", "current costs", "deadline"];
    // in-out property <ProjectModel> modelMock;
    // in-out property <ProjectModel> modelMock1;
    // in-out property <ProjectModel> modelMock2;
    // in-out property <ProjectModel> modelMock3;
    // modelMock: {name: "ProjName", client: "ClientName", email: "EMAIL", tel: "phone", project_start: "heute", project_deadline: "deadline", calculated_costs:"299.99", current_costs: "194.72", mats: []};
    // modelMock1: {name: "ProjName", client: "ClientName", email: "EMAIL", tel: "phone", project_start: "heute", project_deadline: "deadline", calculated_costs:"299.99", current_costs: "194.72", mats: []};
    // modelMock2: {name: "ProjName", client: "ClientName", email: "EMAIL", tel: "phone", project_start: "heute", project_deadline: "deadline", calculated_costs:"299.99", current_costs: "194.72", mats: []};
    // modelMock3: {name: "ProjName", client: "ClientName", email: "EMAIL", tel: "phone", project_start: "heute", project_deadline: "deadline", calculated_costs:"299.99", current_costs: "194.72", mats: []};
    // recentProjects: [modelMock, modelMock1, modelMock2, modelMock];
}