/*

    Author: Justin
    Description: This is the project model that will be used to store the project data

*/

import { Material } from "MaterialModel.slint";
import { ClientModel } from "ClientModel.slint";

export struct ProjectModel {
    id: int,
    name: string,
    // Client
    client: ClientModel,
    //email: string,
    //tel: string,
    project_start: string,
    project_deadline: string,
    calculated_costs: float,
    current_costs: float,
    mats: [Material],
}
