/*

    Author: Justin
    Description: This is the project model that will be used to store the project data

*/

import { Material } from "MaterialModel.slint";

export struct ProjectModel {
    name: string,
    client: string,
    email: string,
    tel: string,
    project_start: string,
    project_deadline: string,
    calculated_costs: string,
    current_costs: string,
    mats: [Material],
}