import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { TextField } from "TextField.slint";
import { Button } from "Button.slint";
import { Palette } from "../Palette.slint";

// TODO(jmeusel): kann später gelöscht
export component Appbar inherits Rectangle {
    
    in-out property <string> buttonText;
        //height: txt + 30px;
        border-color: grey;
        border-width: 3px;
        VerticalLayout {alignment: center;}
    VerticalBox {
        HorizontalBox {
            alignment: space-around;
            padding: 25px;
            HorizontalBox {
                Text {text: "Search:"; color: Palette.accent-color;}
                searchField:= TextField {width: 130px;}
            }
           Button {text: buttonText;}
           Button {
            text: "<";
           }
           
        }
        Rectangle {height: 2px; width: parent.width; background: Palette.accent-color;}
    }



}