/*

    Author: Justin Rauch
    Date: 2024-03-01
    Description: A simple button component

*/

import { Palette } from "../Palette.slint";

export component Button inherits Rectangle {
    in-out property text <=> txt.text; // The text of the button
    in-out property <color> accent; // The color of the button
    callback clicked <=> touch.clicked; // The callback for when the button is clicked
    border-radius: root.height / 4;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? Palette.accent-color.darker(10%) : touch.has-hover ? Palette.accent-color :  Palette.accent-color;
    height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;
    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? Palette.text-color.darker(10%) : Palette.text-color;
    }
    touch := TouchArea { }
}