import { Material } from "../models/MaterialModel.slint";
import { Palette } from "../Palette.slint";
import { LineEdit, Button } from "std-widgets.slint";

export component MatDetailRow inherits Rectangle {

    in-out property <Material> material;
    in-out property <bool> disableBorder;
    in-out property <bool> disableCancelButton;
    callback onEditClick();
    callback onDeleteClick();
    //background: lightblue;
    // TODO(jmeusel): init
    property <length> maxWidth: 175px;
    HorizontalLayout {
        VerticalLayout {
            alignment: center;
            Rectangle {
                padding: 8px;
                border-color: Palette.accent-color;
                border-width: disableBorder ? 0px : 2px;
                HorizontalLayout {
                    alignment: space-between;
                    padding: 8px;
                    Rectangle {
                        width: maxWidth;
                        Text {
                            width: maxWidth;
                            text: material.name;
                            font-size: Palette.font-size * 1px;
                            color: Palette.text-color;
                            overflow: TextOverflow.elide;
                        }
                    }
    
                    Rectangle {
                        max-width: maxWidth;
                        Text {
                            max-width: maxWidth;
                            text: material.type.name == "" ? "–" : material.type.name;
                            font-size: Palette.font-size * 1px;
                            color: Palette.text-color;
                            overflow: TextOverflow.elide;
                        }
                    }
    
                    Rectangle {
                        max-width: maxWidth;
                        Text {
                            max-width: maxWidth;
                            text: material.quantity;
                            font-size: Palette.font-size * 1px;
                            color: Palette.text-color;
                            overflow: TextOverflow.elide;
                        }
                    }
    
                   
                }
            }
        }
        Rectangle {width: 20px;}
        if(!disableCancelButton): Button {
            width: 40px;
            text: "✎";
            clicked => {
                onEditClick()
            }
        }
        Rectangle {width: 10px;}
        Button {
            width: 40px;
            text: "X";
            clicked => {
                onDeleteClick();
            }
        }
    }
}
