import { Material } from "../models/MaterialModel.slint";
import { Palette } from "../Palette.slint";
import { LineEdit } from "std-widgets.slint";

export component MatDetailRow inherits Rectangle {

    in-out property <Material> material;
    in-out property <bool> disableBorder;

    //background: lightblue;
    // TODO(jmeusel): init
    property <length> maxWidth: 175px;
    
    VerticalLayout {
        alignment: center;
        Rectangle {
            padding: 8px;
            border-color: Palette.accent-color;
            border-width: disableBorder ? 0px : 2px;
            HorizontalLayout {
                alignment: space-between;
                padding: 8px;
                Rectangle {
                    width: maxWidth;
                    Text {
                        width: maxWidth;
                        text: material.name;
                        font-size: Palette.font-size * 1px;
                        color: Palette.text-color;
                        overflow: TextOverflow.elide;
                    }
                }
        
                Rectangle {
                    max-width: maxWidth;
                    Text {
                        max-width: maxWidth;
                        text: material.type == "" ? "–" : material.type;
                        font-size: Palette.font-size * 1px;
                        color: Palette.text-color;
                        overflow: TextOverflow.elide;
                    }
                }
        
                Rectangle {
                    max-width: maxWidth;
                    Text {
                        max-width: maxWidth;
                        text: material.quantity;
                        font-size: Palette.font-size * 1px;
                        color: Palette.text-color;
                        overflow: TextOverflow.elide;
                    }
                }
            }
        }
    }
}
