import { HorizontalBox } from "std-widgets.slint";
import { Palette } from "../Palette.slint";
import { Material } from "../models/MaterialModel.slint";


export  component MaterialAlertShort inherits HorizontalLayout {

    in-out property <string> materialName;
    in-out property <int> quantity;
    in-out property <int> thresholdValue;
    property <length> txt;
    in-out property <Material> material;
    txt: Palette.font-size * 1px;

    Rectangle {
        height: txt + 46px;
        border-color: grey;
        border-width: 3px;
        HorizontalBox {
            Text {
                text: root.materialName;
                font-size: txt;
                color: Palette.accent-color;
                vertical-alignment: center;
            }

            Rectangle { }

            Text {
                text: root.quantity;
                font-size: txt;
                color: quantity <= thresholdValue ? Colors.red : Palette.accent-color;
                vertical-alignment: center;
            }
        }
    }
}
