import { HorizontalBox } from "std-widgets.slint";
import { Palette } from "ui/Palette.slint";



export  component MaterialAlertShort inherits HorizontalBox {

    in-out property <string> materialName;
    in-out property <int> count;
    property <length> txt;
    txt: Palette.font-size * 1px;

    Rectangle {
        height: txt + 30px;
        border-color: grey;
        border-width: 3px;
        HorizontalBox {
            Text {
                text: root.materialName;
                font-size: txt;
                color: Palette.accent-color;
                vertical-alignment: center;
            }

            Rectangle { }

            Text {
                text: root.count;
                font-size: txt;
                color: Palette.accent-color;
                vertical-alignment: center;
            }
        }
    }
}
