import { VerticalBox, HorizontalBox, StandardButton } from "std-widgets.slint";
import { TextField } from "../Widgets/TextField.slint";
import { Constants } from "../Constants.slint";
import { Button } from "../Widgets/Button.slint";


export component MaterialPopUp inherits Rectangle {
    // TODO(jmeusel): Type ändern
    in-out property <bool> showPopUp;
    in-out property <string> nameController;
    in-out property <string> priceController;
    in-out property <string> typeController;
    in-out property <string> amountController;
    in-out property <string> rememberWhenController;
    in-out property <string> descriptionController;
    in-out property <string> thresholdValueController;
    visible: showPopUp;


    /*
    DB model:
    pub struct Material {
    pub id: i32,
    pub name: String,
    pub description: String,
    pub type_id: i32,
    pub amount: i32,
    pub costs: f32,
    pub threshold_value: i32,
}

    */
    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: start;
            padding-top: 200px;
            Rectangle {
                background: lightgray;
                width: 400px;
                height: 460px;
                VerticalBox {
                    HorizontalBox {
                        Text {
                            text: Constants.name + ":";
                        }
        
                        TextField {
                            text: nameController;
                        }
                    }
        
                    HorizontalBox {
                        Text {
                            text: Constants.price + ":";
                        }
        
                        TextField {
                            text: priceController;
                        }
                    }
        
                    HorizontalBox {
                        Text {
                            text: Constants.type + ":";
                        }
        
                        TextField {
                            text: typeController;
                        }
                        
                    }

                    HorizontalBox {
                        Text {
                            text: Constants.amount + ":";
                        }
        
                        TextField {
                            text: amountController;
                        }
                        
                    }
                    HorizontalBox {
                        Text {
                            text: Constants.remember_when + ":";
                        }
        
                        TextField {
                            text: rememberWhenController;
                        }
                        
                    }
                    HorizontalBox {
                        Text {
                            text: Constants.description + ":";
                        }
        
                        TextField {
                            text: descriptionController;
                        }
                        
                    }
                    HorizontalBox {
                        Text {
                            text: Constants.remember_when + ":";
                        }
        
                        TextField {
                            text: thresholdValueController;
                        }
                        
                    }
                    
        
                    HorizontalBox {
                        Button {
                            text: "Cancel";
                            clicked => {
                                // TODO(jmeusel): cancel
                        }
                        }
        
                        Button {
                            text: "Save";
                            clicked => {
                                // TODO(jmeusel): Save
                        }
                        }
                    }
                }
            }
        }
    }
}


