import { VerticalBox } from "std-widgets.slint";
import { Palette } from "../Palette.slint";


 component WMSText inherits Text {
    in-out property <string> title;
    font-size: Palette.font-size * 1px;
    color: Palette.text-color;
    text: title;
    width: 200px;
    overflow: TextOverflow.elide;
}

export component ProjectRowShort inherits Rectangle {
    //props
    property <length> txt;
    txt: Palette.font-size * 1.5px;
    in-out property <string> project;
    in-out property <string> client;
    in-out property <string> costs;
    in-out property <string> deadline;
    //callback clicked <=> touch.clicked;
    callback clicked <=> touch.clicked; // The callback for when the button is clicked


    background: Palette.accent-color;
    height: 65px;
    border-color: white;
    border-width: 2px;
    border-radius: 8px;

    Rectangle {
        // TODO(jmeusel): response für click anpassen 
        HorizontalLayout {
            x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
            y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
            alignment: stretch;
            padding: 16px;
            WMSText {
                title: project;
                font-size: txt;
            }
            Rectangle {}
            WMSText {
                title: client;
                font-size: txt;
            }
            Rectangle {}
            WMSText {
                title: costs;
                font-size: txt;
            }
            Rectangle {}
            WMSText {
                title: deadline;
                font-size: txt;
            }
        }
    }

    touch := TouchArea {}

}
