/*

    Author: Jasha
    Description: A horizontal card showing the information of a project

*/
import { HorizontalBox, VerticalBox, Button } from "std-widgets.slint";
import { TextField } from "TextField.slint";
import { Palette } from "../Palette.slint";
export component ProjectDetailRow inherits HorizontalLayout {

    in-out property <string> title;
    in-out property <string> textFieldName <=> textFieldName.text;
    // TODO(jmeusel): Hier muss noch etwas getan werden, da der Controller keine Werte nimmt
    in-out property <string> textFieldName2;
    property <length> customHeight;
    //customHeight: 50px;
    alignment: space-between;
    Text {
        vertical-alignment: center;
        text: title;
        color: Palette.accent-color;
        font-size: Palette.font-size * 2px;
    }

    textFieldName := TextField { 
        height: Palette.font-size * 2px;
        width: 300px;
    }
}


