import { Palette } from "../Palette.slint";
import { HorizontalBox } from "std-widgets.slint";

// TODO(jmeusel): optionalen X button hinzufügen
// TODO(jmeusel): ggf. die Height der Boxen begrenzen.

export component RowBox inherits HorizontalBox {
    in-out property <string> label;
        Rectangle {
            border-radius: 8px;
            border-color: black;
            background: Palette.accent-color;
            border-width: 2px;
            height: 50px;
            width: 150px;
            Text {
                //padding-right: 20px;
                font-size: Palette.font-size * 1px;
                text: label;  
            }
        }
}


// TODO(jmeusel): Labels auslagern (von außen reingeben)
export component RowTest inherits Rectangle {

    // TODO(jmeusel): types anpassen
    in property <string> text;
    in-out property <string> project;
    in-out property <string> client;
    in-out property <string> costs;
    in-out property <string> deadline;

    border-color: green;
    border-width: 2px;
    HorizontalBox {
        width: 200px;
        alignment: LayoutAlignment.space-between;
        RowBox {
            label: project;
        }
        Rectangle {
            width: 25px;
        }
       RowBox {
        label: client;
    }
        Rectangle {
            width: 25px;
        }
        RowBox {
            label: costs;
        }
        Rectangle {
            width: 25px;
        }
        RowBox {
            label: deadline;
        }
    }
}


