/*

    Author: Justin Rauch
    Date: 2024-03-12
    Description: LineEdit implementation with out styles

*/

import { Palette } from "../Palette.slint";
import { TextEdit } from "std-widgets.slint";

export component TextField inherits Rectangle {
    in-out property <string> text <=> lineEdit.text; // Text in the line edit
    width: 150px;
    height: 30px;
    border-color: Palette.accent-color;
    border-width: 1px;
    border-radius: 5px;
    background: Palette.control-color;
    lineEdit := TextInput {
        vertical-alignment: center;
        height: parent.height - 2px;
        width: parent.width - 10px;
        font-size: 10px;
        opacity: 0.5;
        selection-background-color: Palette.accent-color;
        color: Palette.text-color;
    }
}