import { VerticalBox, HorizontalBox, StandardButton } from "std-widgets.slint";
import { TextField } from "../Widgets/TextField.slint";
import { Constants } from "../Constants.slint";
import { Button } from "../Widgets/Button.slint";
import { ClientModel } from "../models/ClientModel.slint";
import { Backend } from "../Backend.slint";


export component ClientPopUp inherits Rectangle {

    in-out property <ClientModel> client;

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: start;
            padding-top: 200px;
            Rectangle {
                background: lightgray;
                width: 400px;
                height: 260px;
                VerticalBox {
                    HorizontalBox {
                        Text {
                            text: Constants.first_name;
                        }

                        clientFirstName := TextField {
                            text: client.firstName;
                        }
                    }

                    HorizontalBox {
                        Text {
                            text: Constants.last_name;
                        }

                        clientLastName := TextField {
                            text: client.lastName;
                        }
                    }

                    HorizontalBox {
                        Text {
                            text: Constants.phone + ":";
                        }

                        ClientPhone := TextField {
                            text: client.phone;
                        }
                    }

                    HorizontalBox {
                        Button {
                            text: Constants.cancel;
                            clicked => {
                                Backend.hideClientPopUp();
                            }
                        }

                        Button {
                            text: Constants.save;
                            clicked => {
                                Backend.saveClient(
                                         clientFirstName.text,
                                         clientLastName.text,
                                         ClientPhone.text,
                                      );
                            }
                        }
                    }
                }
            }
        }
    }
}
