import { VerticalBox, HorizontalBox, StandardButton } from "std-widgets.slint";
import { TextField } from "../Widgets/TextField.slint";
import { Constants } from "../Constants.slint";
import { Button } from "../Widgets/Button.slint";
import { ClientModel } from "../models/ClientModel.slint";
import { Backend } from "../Backend.slint";
import { Palette } from "../Palette.slint";
import { ErrorMessage } from "../Widgets/Errormessage.slint";


export component ClientPopUp inherits Rectangle {

    in-out property <ClientModel> client;
    in-out property <string> errorMessage;

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: start;
            padding-top: 200px;
            Rectangle {
                background: Palette.control-color;
                width: 400px;
                height: 260px;
                border-width: 4px;
                border-color: Palette.accent-color;
                border-radius: 6px;
                VerticalBox {
                    HorizontalBox {
                        Text {
                            text: Constants.first_name;
                        }

                        clientFirstName := TextField {
                            text: client.firstName;
                        }
                    }

                    HorizontalBox {
                        Text {
                            text: Constants.last_name;
                        }

                        clientLastName := TextField {
                            text: client.lastName;
                        }
                    }

                    HorizontalBox {
                        Text {
                            text: Constants.phone + ":";
                        }

                        ClientPhone := TextField {
                            text: client.phone;
                        }
                    }

                    HorizontalBox {
                        Button {
                            text: Constants.cancel;
                            clicked => {
                                Backend.hideClientPopUp();
                            }
                        }

                        Button {
                            text: Constants.save;
                            clicked => {
                                Backend.saveClient(
                                         clientFirstName.text,
                                         clientLastName.text,
                                         ClientPhone.text,
                                      );
                            }
                        }
                    }
                    alignment: center;
                    ErrorMessage {
                        title: errorMessage;
                    }
                }
            }
        }
    }
}
