/*

    Author: Jasha
    Description: 

*/
import { WMSAppbar } from "../Widgets/WMSAppbar.slint";
import { VerticalBox, HorizontalBox, GridBox, Slider } from "std-widgets.slint";
import { TextField } from "../Widgets/TextField.slint";
import { Button } from "../Widgets/Button.slint";
import { Palette } from "../Palette.slint";
import { LagerRow } from "../Widgets/Lager/LagerRow.slint";
import { Material } from "../models/MaterialModel.slint";
import { Constants } from "../Constants.slint";
import { Backend } from "../Backend.slint";
import { TitleSection } from "../Widgets/TitleSeciton.slint";


// TODO(jmeusel): Material Count sollte Rot angezeigt werden falls der Wert unterschritten wird
export component LagerOverview inherits VerticalBox {
    in-out property <[Material]> materials;
    in-out property <string> searchText;
    property <length> topPadding: 20px;

    alignment: start;
    Rectangle {
        height: topPadding;
    }

    TitleSection {
        title: Constants.warehouse_management;
    }

    WMSAppbar {
        buttonTitleFirst: "Add Material";
        showSecondButton: true;
        onFirstButtonPressed => {
            Backend.showAddNewMaterialPopUp();
        }
        edited => {
            Backend.search-material(self.searchText);
        }
        buttonTitleSecond: "Add Material Type";
        secondButtonWidth: 167px;
        onSecondButtonPress => {
            Backend.showAddNewMaterialTypePopUp();
        }
    }

    Rectangle {
        height: 80px;
    }

    HorizontalBox {
        alignment: LayoutAlignment.start;
        
    }

    for material[i] in materials: LagerRow {
        name: materials[i].name;
        price: materials[i].price;
            type: materials[i].type;
        amount: materials[i].quantity;
        rememberWhen: "never";
        description: materials[i].description;
        onEditClicked => {
        }
        onDeleteClicked => {}
    }
}
