/*

    Author: Justin Rauch, Jasha Meusel
    Date: 2024-03-12
    Description: Login Window for the Workshop Client

*/

import { Palette } from "../Palette.slint";

import { VerticalBox, HorizontalBox } from "std-widgets.slint";

import { ToggleSwitch } from "../Widgets/ToggleSwitch.slint";
import { TextField } from "../Widgets/TextField.slint";
import { CheckBox } from "../Widgets/CheckBox.slint";
import { Button } from "../Widgets/Button.slint";

export component LoginView inherits Rectangle {
    in-out property<string> username <=> username.text;
    in-out property<string> password <=> password.text;
    callback request-login();
    HorizontalBox {
        alignment: center;
        VerticalBox {
            alignment: center;

            Text {
                text: "Username";
                color: Palette.text-color;
                font-size: Palette.font-size * 1.2px;
            }
            username := TextField {
                height: root.width * 0.03;
                width: root.width * 0.2;
            }
    
            Text {
                text: "Password";
                color: Palette.text-color;
                font-size: Palette.font-size * 1.2px;
            }
            password := TextField {
                height: root.width * 0.03;
                width: root.width * 0.2;
            }
            
            HorizontalBox {
                Rectangle {} // Spacer
            }
    
            Button {
                text: "Login";
                clicked => {
                    root.request-login();
                }
                width: root.width * 0.2;
                height: root.width * 0.04;
            }
        }
    }
}
