/*

    Author: Justin Rauch, Jasha Meusel
    Date: 2024-03-12
    Description: Login Window for the Workshop Client

*/

import { Palette } from "../Palette.slint";

import { VerticalBox, HorizontalBox } from "std-widgets.slint";

import { ToggleSwitch } from "../Widgets/ToggleSwitch.slint";
import { TextField } from "../Widgets/TextField.slint";
import { CheckBox } from "../Widgets/CheckBox.slint";
import { Button } from "../Widgets/Button.slint";

export component LoginView inherits Rectangle {
    in-out property<string> username <=> username.text;
    in-out property<string> password <=> password.text;
    in-out property<string> login_error <=> login_error.text;
    callback request-login();
    HorizontalBox {
        alignment: center;
        VerticalBox {
            alignment: center;

            Text {
                text: "Username";
                color: Palette.text-color;
                font-size: Palette.font-size * 1.2px;
            }
            username := TextField {
                height: root.width * 0.027;
                width: root.width * 0.2;
            }
    
            Text {
                text: "Password";
                color: Palette.text-color;
                font-size: Palette.font-size * 1.2px;
            }
            password := TextField {
                height: root.width * 0.027;
                width: root.width * 0.2;
            }
            
            Rectangle {
                height: root.width * 0.02;
                login_error := Text {
                    color: red;
                    font-size: Palette.font-size * 0.5px;
                    horizontal-alignment: center;
                    overflow: elide; 
                }    
            }

            Button {
                text: "Login";
                clicked => {
                    root.request-login();
                }
                width: root.width * 0.2;
                height: root.width * 0.04;
            }
        }
    }
}
