/*

    Author: Jasha
    Description: Overview of all projects with the option of a search

*/

import { HorizontalBox, VerticalBox, ScrollView } from "std-widgets.slint";
import { WMSAppbar } from "../Widgets/WMSAppbar.slint";
import { Constants } from "../Constants.slint";
import { ProjectRowShort } from "../Widgets/ProjectRowShort.slint";
import { Palette } from "../Palette.slint";
import { Button } from "../Widgets/Button.slint";
import { ProjectModel } from "../models/ProjectModel.slint";
import { TitleSection } from "../Widgets/TitleSeciton.slint";
import { Backend } from "../Backend.slint";


export component ProjectManagement inherits ScrollView {

    in-out property <[ProjectModel]> allProjects;

    VerticalBox {
        alignment: start;
        TitleSection {
            title: Constants.project_overview;
        }

        WMSAppbar {
            showSecondButton: true;
            buttonTitleFirst: Constants.create_new_project;
            buttonTitleSecond: Constants.add_client;
            firstButtonWidth: 200px;
            onFirstButtonPressed => {
                Backend.create_new_project();
            }
            onSecondButtonPress => {
                Backend.showAddNewClientPopUp();
            }
            edited => {
                Backend.search-project(self.searchText);
            }
        }

        Rectangle {
            height: 50px;
        }

        HorizontalLayout {
            ProjectRowShort {
                project: "Project Name";
                client: "Client";
                costs: "Costs";
                deadline: "Deadline";
                turnOffBackgroundAndBorder: true;
            }
            // invisible Rectangle to align with the listView lower in the Code
            Rectangle {
            width: 35px;
            height: 40px;
        }
        }
        // iterates over the list of AllProjects
        for project[i] in allProjects: HorizontalLayout {
            ProjectRowShort {
                client: allProjects[i].client.lastName;
                project: allProjects[i].name;
                costs: allProjects[i].current_costs;
                deadline: allProjects[i].project_deadline;
                clicked => {
                    Backend.route-to-project-i(allProjects[i].id);
                }
            }
            Rectangle {width: 10px;}
            Button {
            width: 35px;
            height: 50px;
            text: "X";
            fontSizeMultiplier: 1.5px;
            clicked => {
                Backend.delete-project-i(allProjects[i].id);
            }
        }
        }
        Rectangle {
            max-width: 20px;
        }
    }
}
