/*

    Author: Justin
    Description: Backend interface with all callbacks

*/
import { Material } from "../ui/models/MaterialModel.slint";
import { ProjectModel } from "../ui/models/ProjectModel.slint";


export global Backend {
    /*

        Callbacks

    */
    // Login View
    callback request-login();
    callback request-exit();

    // Project View
    callback request-logout();

    // Project Detail View
    // parameter: ID of the material to delete
    callback deleteMaterial(int);
    callback save-project-and-used-materials();
    
    // Project Management View
    callback create_new_project();
    callback add-new-client();

    // AppBar
    callback goBack();

    // LagerOverview
    callback save-materials();
    callback add-material();

    // Navigation:
    callback route-to-project-management();
    callback route-to-warehouse-management();
    // parameter: ID of the project to show
    callback route-to-project-i(int);
    callback route-to-LagerOverview();
    callback showAddNewClientPopUp ();
    callback showAddNewMaterialPopUp ();


    // TODO(jmeusel): Suche???????? aulagern jewails für kontent oder kann man das anders regeln?
    //// Justin: Mach eine function die mir einfach den inhalt des searchfeldes via parameter übergibt
    ////         jeweils für project und material



    /*

        Variables

    */
    // LoginView
    in-out property <string> username;
    in-out property <string> password;
    in-out property <string> login_error;

    // ProjectView 
    in-out property <[ProjectModel]> recentProjects;
    in-out property <[Material]> materialAlerts;

    // ProjectManagement
    in-out property <[ProjectModel]> allProjects;

    // ProjectDetailView
    in-out property <ProjectModel> project;

    // LagerOverview
    in-out property <[Material]> materials;

    // Variables for routing and navigation
    in-out property <bool> showClientPopUp;
    in-out property <bool> showMaterialPopUp;
    in-out property <bool> loginView: true;
    in-out property <bool> projectView: false;
    in-out property <bool> projectManagementView: false;
    in-out property <bool> projectDetailView: false;
    in-out property <bool> lagerOverviewView: false;
}