/*

    Author: Justin Rauch
    Date: 2024-03-01
    Description: A simple checkbox component

*/

export component CheckBox inherits Rectangle {
    callback checked;
    in-out property <string> text;
    in-out property <bool> toggled;
    in-out property<bool> enabled <=> touch-area.enabled;
    height: 20px;
    horizontal-stretch: 0;
    vertical-stretch: 0;

    HorizontalLayout {
        spacing: 8px;
        indicator := Rectangle {
            width: 20px;
            border-width: 1px;
            border-radius: root.height / 5;
            border-color: self.background.darker(25%);
            background: root.enabled ? #219fd5 : #3f3f3f;

            checkMark := Rectangle {
                width: root.height;
                height: checkMark.width;
                border-radius: root.height / 5;
                property <float> a: root.toggled ? 1 : 0;
                background: root.toggled ? #219fd5 : (root.enabled ? #3f3f3f : gray);
                Rectangle {
                    border-radius: 5px;
                    width: checkMark.width * 0.5;
                    height: checkMark.height * 0.5;
                    background: root.toggled ? white : transparent;
                    animate background { duration: 200ms; easing: ease;}
                }
                animate a, background { duration: 200ms; easing: ease;}
            }
        }

        txt := Text {
            min-width: max(100px, self.preferred-width);
            text: root.text;
            vertical-alignment: center;
            color: root.enabled ? white : gray;
        }

    }

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
        clicked => {
            if (root.enabled) {
                root.toggled = !root.toggled;
                root.checked();
            }
        }
    }

    width: indicator.width + 8px + txt.preferred-width;
}