export global Constants {
    in-out property <string> project: "Project";
    in-out property <string> project_name: "Projectname:";
    in-out property <string> project_details: "Project Details";
    in-out property <string> project_title: "Workshop management\nSystem";

    in-out property <string> name: "Name";
    in-out property <string> client: "Client";
    in-out property <string> phone: "Phone";
    in-out property <string> email: "E-mail";
    in-out property <string> project_start: "Project-start";
    in-out property <string> project_deadline: "Project-deadline";
    in-out property <string> currentCosts:"Current costs";
    in-out property <string> calculated_costs:"Calculated costs";
    in-out property <string> materials:"Materials";
    in-out property <string> login: "Login";
    in-out property <string> logout:"Logout";
    in-out property <string> create_new_project:"Create new Project";
    in-out property <string> search:"Search:";
    in-out property <string> project_management:"Project - management";
    in-out property <string> warehouse_management:"Warehouse - management";
    in-out property <string> latest_projects:"Latest Projects:";
    in-out property <string> mat_alert:"Material alert:";
    in-out property <string> warehouse_overview:"Warehouse - overview";
    in-out property <string> project_overview:"Project - overview";
    in-out property <string> add_new_mat:"Add new Material";
    in-out property <string> remember_when:"Remember when";
    in-out property <string> amount:"Amount";
    in-out property <string> description:"Description";
    in-out property <string> type:"Type";
    in-out property <string> price:"Price";
    in-out property <string> cancel:"Cancel";
    in-out property <string> save:"Save";
    in-out property <string> show_more: "Show more";
    in-out property <string> add_client: "Add Client";
    in-out property <string> add_material: "Add Material";
    in-out property <string> first_name: "First name:";
    in-out property <string> last_name: "Last name:";
    in-out property <string> save_project: "Save Project";





}