/*

    Author: Justin, Jasha
    Date: 2024-03-01
    Description: Main Window for the WorkshopClient

*/

// Importing constants and other stuff
import { Palette } from "Palette.slint";
import { Backend } from "Backend.slint";
import { Constants } from "Constants.slint";

// Importing the Standard Widgets
import { VerticalBox, ComboBox, LineEdit, Button } from "std-widgets.slint";

// Importing self made Widgets
import { ToggleSwitch } from "Widgets/ToggleSwitch.slint";
import { CheckBox } from "Widgets/CheckBox.slint";

// Importing the Views
import { LoginView } from "Views/LoginView.slint";
import { ProjectView } from "Views/ProjectView.slint";
import { ProjectManagement } from "Views/ProjectManagement.slint";
import { ProjectDetailView } from "Views/ProjectDetailView.slint";
import { LagerOverview } from "Views/LagerOverview.slint";
import { ClientPopUp } from "../ui/Views/ClientPopUp.slint";

import { MockModel } from "../ui/models/MockModels.slint";

// Exporting the Backend
export { Backend }

export component WorkshopClient inherits Window {
    //width: 1920px;
    //height: 1080px;

    // Properties
    in-out property<string> username;
    in-out property<string> password;
    in-out property<string> login_error;

    // Bools for views
    in-out property <bool> loginView: true;
    in-out property <bool> projectView: false;
    in-out property <bool> projectManagementView: false;
    in-out property <bool> projectDetailView: false;
    in-out property <bool> lagerOverviewView: false;
    // isn´t a view but works like
    in-out property <bool> clientPopUp: false;

    // Variables for the window itself
    background: Palette.background-color;
    title: "Workshop Management Client";

    // Bar in the accent color for design purposes
    VerticalLayout {
        padding: 10px;
        Rectangle {
            width: parent.width - 20px;
            height: 2px;
            background: Palette.accent-color;
        }
    }


    // Actual content
    LoginView {
        username <=> root.username;
        password <=> root.password;
        login_error <=> root.login_error;
        //visible <=> root.loginView;
        visible: false;
    }
    ProjectView {
        //visible <=> root.projectView;
        visible: false;
        recentProjects: MockModel.recentProjects;
        materialAlerts: MockModel.materials;
    }
    ProjectManagement {
        //visible <=> root.projectManagementView;
        visible: false;
        allProjects: MockModel.allProjectsMockList;
    }
    ProjectDetailView {
        //visible <=> root.projectDetailView;
        visible: true;
        project: MockModel.projectWithMats;
        materialTypes: MockModel.materialTypesMock;
    }

    LagerOverview {
        //visible <=> root.lagerOverviewView;
        visible: false;
    }

    // Bar in the accent color for design purposes
    VerticalLayout {
        padding-top: parent.height - 10px;
        padding: 10px;
        Rectangle {
            width: parent.width - 20px;
            height: 2px;
            background: Palette.accent-color;
        }
    }

    // Popup for the Client
    ClientPopUp {
        visible: false;
        showPopUp: Backend.showPopUp();
    }

}
