/*

    Author: Justin, Jasha
    Date: 2024-03-01
    Description: Main Window for the WorkshopClient

*/

// Importing constants and other stuff
import { Palette } from "Palette.slint";
import { Backend } from "Backend.slint";
import { Constants } from "Constants.slint";

// Importing the Standard Widgets
import { VerticalBox, ComboBox, LineEdit, Button } from "std-widgets.slint";

// Importing self made Widgets
import { ToggleSwitch } from "Widgets/ToggleSwitch.slint";

// Importing the Views
import { LoginView } from "Views/LoginView.slint";
import { ProjectView } from "Views/ProjectView.slint";
import { ProjectManagement } from "Views/ProjectManagement.slint";
import { ProjectDetailView } from "Views/ProjectDetailView.slint";
import { LagerOverview } from "Views/LagerOverview.slint";
import { ClientPopUp } from "../ui/Views/ClientPopUp.slint";

import { MockModel } from "../ui/models/MockModels.slint";
import { MaterialPopUp } from "Widgets/MaterialPopUp.slint";
import { MaterialTypePopUp } from "Widgets/MaterialTypePopUp.slint";

// Exporting the Backend
export { Backend }

export component WorkshopClient inherits Window {
    width: 1920px;
    height: 1080px;

    // Variables for the window itself
    background: Palette.background-color;
    title: "Workshop Management Client";

    // Bar in the accent color for design purposes
    VerticalLayout {
        padding: 10px;
        Rectangle {
            width: parent.width - 20px;
            height: 2px;
            background: Palette.accent-color;
        }
    }

    // Actual content
    LoginView {
        //FUNCTIONS CHECK
        username <=> Backend.username;
        password <=> Backend.password;
        login_error <=> Backend.login_error;
        visible <=> Backend.loginView;
        //visible: false;
    }

    ProjectView {
        // Fertig, bis auf Errormeldung
        //visible <=> Backend.projectView;
        visible: false;
        recentProjects: MockModel.recentProjects;
        //materialAlerts: MockModel.materials;
        materialAlerts: MockModel.materials;
    }

    ProjectManagement { // Fertig bis auf error und scrollbereich
        //visible <=> Backend.projectManagementView;
        visible: false;
        //allProjects: MockModel.allProjectsMockList;
        allProjects: MockModel.allProjectsMockList;
    }

    ProjectDetailView {
        //visible <=> Backend.projectDetailView;
        visible: true;
        project: MockModel.projectWithMats;
        clients: MockModel.clientListAsString;
    }

    LagerOverview {
        //visible <=> Backend.lagerOverviewView;
        visible: false;
        materials: MockModel.materialList;
    }

    // Bar in the accent color for design purposes
    VerticalLayout {
        padding-top: parent.height - 10px;
        padding: 10px;
        Rectangle {
            width: parent.width - 20px;
            height: 2px;
            background: Palette.accent-color;
        }
    }

    ClientPopUp {
        //visible <=> Backend.showClientPopUp;
        visible: false;
    }

    MaterialPopUp {
        //visible <=> Backend.showMaterialPopUp;
        visible: false;
    }

    MaterialTypePopUp {
        //visible <=> Backend.showMaterialTypePopUp;
        visible: false;
    }
}
